### ISSUE TITLE
Need Clarity about the library.

### ISSUE THREAD

**Issue by ganeshsingamaneni** [sang-sakarin/py2c2p#1]
Hi iam trying to do the same thing as 2c2p payment provide service, i have gone through the py2c2p code and i didn't understand few things from your code like APIEnvironment.SANDBOX = 'https://demo2.2c2p.com/2C2PFrontend/PaymentActionV2' , i have gone through the 2c2p developer document and found the sandbox url is "https://demo2.2c2p.com/2C2PFrontEnd/RedirectV3/payment".
And there are three types of API's in 2c2p, i want to know to which API your library comes under.
And if possible i want to support your library.

**Comment by sang-sakarin** [comment]
Thank for the interesting library. Right now, it's only supported in section mobile Sdk (server side)

 https://developer.2c2p.com/docs/mobile-v4-how-it-work
